// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentVariant } from "./ComponentVariant";
import type { ComponentVariantArea } from "./ComponentVariantArea";
import type { Node } from "./Node";

export type ComponentDefinition = { id: string, name: string, source_node: Node, variant_area?: ComponentVariantArea | null, variants: Array<ComponentVariant>, };
