// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentVariantAreaLayout } from "./ComponentVariantAreaLayout";
import type { LayoutPadding } from "./LayoutPadding";

export type ComponentVariantArea = { layout: ComponentVariantAreaLayout, gap: number, padding: LayoutPadding, };
