// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentPropertyType } from "./ComponentPropertyType";

export type ComponentProperty = { name: string, value: string, type: ComponentPropertyType, };
