// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentProperty } from "./ComponentProperty";
import type { Node } from "./Node";

export type ComponentVariant = { id: string, name: string, properties: Array<ComponentProperty>, source_node?: Node | null, };
