// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Page } from "./Page";

export type DesignFile = { id: string, name: string, version: number, pages: Array<Page>, };
