// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeComponentMapping } from "./CodeComponentMapping";
import type { ComponentDefinition } from "./ComponentDefinition";
import type { DesignStyle } from "./DesignStyle";
import type { DesignToken } from "./DesignToken";
import type { DesignTokenSet } from "./DesignTokenSet";
import type { Page } from "./Page";

export type DesignFile = { id: string, name: string, version: number, token_sets?: Array<DesignTokenSet>, tokens: Array<DesignToken>, styles?: Array<DesignStyle>, components: Array<ComponentDefinition>, code_mappings?: Array<CodeComponentMapping>, pages: Array<Page>, };
