// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeSummary } from "./NodeSummary";

export type DesignContext = { file_id: string, file_name: string, node_count: number, nodes: Array<NodeSummary>, };
