// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentDefinition } from "./ComponentDefinition";
import type { DesignToken } from "./DesignToken";
import type { Page } from "./Page";

export type DesignFile = { id: string, name: string, version: number, tokens: Array<DesignToken>, components: Array<ComponentDefinition>, pages: Array<Page>, };
