// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DesignTokenType } from "./DesignTokenType";

export type DesignToken = { id: string, name: string, type: DesignTokenType, value: string, };
