// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DesignStyleType } from "./DesignStyleType";

export type DesignStyle = { id: string, name: string, type: DesignStyleType, value: string, };
