// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GridArea = { name: string, column: number, row: number, column_span: number, row_span: number, };
