// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridTrackType } from "./GridTrackType";

export type GridTrack = { type: GridTrackType, value?: number | null, };
