// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LayoutJustifyContent = "start" | "center" | "end" | "space_between" | "space_around" | "space_evenly";
