// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeContent } from "./NodeContent";
import type { NodeKind } from "./NodeKind";
import type { Size } from "./Size";
import type { Style } from "./Style";
import type { Transform } from "./Transform";

export type Node = { id: string, kind: NodeKind, name: string, children: Array<Node>, transform: Transform, size: Size, style: Style, content: NodeContent, };
