// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeContent = { "type": "empty" } | { "type": "text", value: string, font_size: number, font_family: string, writing_mode?: string | null, typography_token?: string | null, } | { "type": "image", asset_id: string, natural_width?: number | null, natural_height?: number | null, fit_mode?: string | null, };
