// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridTrack } from "./GridTrack";
import type { LayoutAlignContent } from "./LayoutAlignContent";
import type { LayoutAlignItems } from "./LayoutAlignItems";
import type { LayoutDirection } from "./LayoutDirection";
import type { LayoutJustifyContent } from "./LayoutJustifyContent";
import type { LayoutMode } from "./LayoutMode";
import type { LayoutPadding } from "./LayoutPadding";
import type { LayoutSizing } from "./LayoutSizing";
import type { LayoutWrap } from "./LayoutWrap";

export type NodeLayout = { mode: LayoutMode, direction: LayoutDirection, wrap: LayoutWrap, align_items: LayoutAlignItems, justify_content: LayoutJustifyContent, align_content: LayoutAlignContent, width_sizing?: LayoutSizing, height_sizing?: LayoutSizing, gap: number, row_gap?: number | null, grid_columns?: number | null, grid_rows?: number | null, column_gap?: number | null, grid_column_tracks?: Array<GridTrack> | null, grid_row_tracks?: Array<GridTrack> | null, padding: LayoutPadding, };
