// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportPresetFormat } from "./ExportPresetFormat";

export type NodeExportPreset = { id: string, format: ExportPresetFormat, scale: number, suffix: string, };
