// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutAlignItems } from "./LayoutAlignItems";
import type { LayoutDirection } from "./LayoutDirection";
import type { LayoutJustifyContent } from "./LayoutJustifyContent";
import type { LayoutMode } from "./LayoutMode";
import type { LayoutPadding } from "./LayoutPadding";

export type NodeLayout = { mode: LayoutMode, direction: LayoutDirection, align_items: LayoutAlignItems, justify_content: LayoutJustifyContent, gap: number, padding: LayoutPadding, };
