// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bounds } from "./Bounds";
import type { NodeKind } from "./NodeKind";

export type NodeSummary = { id: string, kind: NodeKind, name: string, bounds: Bounds, child_count: number, };
