// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BooleanPathOperation } from "./BooleanPathOperation";

export type PathBooleanRelation = { operation: BooleanPathOperation, source_node_ids: Array<string>, };
