// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Style = { fill: string, stroke: string | null, stroke_width: number, opacity: number, };
