// This file was generated by ts-rs. Do not edit this file manually.

import type { StrokeCap } from "./StrokeCap";
import type { StrokeJoin } from "./StrokeJoin";
import type { StrokeMarker } from "./StrokeMarker";

export type Style = { fill: string, fill_token?: string | null, fill_style?: string | null, stroke: string | null, stroke_width: number, stroke_cap?: StrokeCap | null, stroke_join?: StrokeJoin | null, stroke_dasharray?: Array<number> | null, stroke_start_marker?: StrokeMarker | null, stroke_end_marker?: StrokeMarker | null, opacity: number, effect_shadow?: string | null, effect_shadows?: Array<string> | null, effect_shadow_token?: string | null, effect_shadow_style?: string | null, };
